### ISSUE TITLE
[Issue? Question?] Cannot set TV Volume, and also does this mod support to set the mod items volume?

### ISSUE THREAD

**Issue by CoolLKKPS** [Kesomannen/KeepItDown#1]
so im doing my modpack, hopefully u can deal with that, really useful mod thx

**Comment by Kesomannen** [comment]
Sadly mods need to add support manually (there's a guide in the README). I will add a TV volume setting though.

**Comment by CoolLKKPS** [comment]
@Kesomannen ok and uh, can u make LethalSetting as soft dependency? i more like to use LethalConfig bc that interface are more friendly

**Comment by CoolLKKPS** [comment]
LethalSetting are not really useful in my modpack, in fact it will auto pop-up when open the game setting (a bit painful), not sure this issue is from LethalSetting itself or not; and can't just press cancel to undo the change, bc those reason, i think i will be more welcome for LethalConfig

**Comment by Kesomannen** [comment]
Yeah I looked into switching over to LethalConfig, but the API doesn't allow for the search feature :/ If I make LethalSettings a soft dependency people might miss it completely, which really takes away from the mod. I could add a notification somewhere to let the player know to install LethalSettings or LethalConfig. Maybe I'll also make a pull request to LethalConfig to allow for my use case and, if it gets accepted, switch over.

**Comment by CoolLKKPS** [comment]
Edited: i saw the comment u made in LethalConfig, well i thought u point lethalconfig can't able to change specified volume in real-time, i was wrong, i will continue track that feature request, thx for ur mod

**Comment by CoolLKKPS** [comment]
forget about my last comment, well im dumb, so lethalsetting support to search specified items to adjust specified volume but lethalconfig can't, i thought u say lethalconfig cannot able to change the specified volume in real-time, after i watch ur code pretty sure i was wrong, sorry im might a bit tired at that moment

**Comment by Kesomannen** [comment]
All good, all good 😄 I have added some basic LethalConfig support (switching the inputs to sliders and making the names prettier). There is however an issue because the LethalConfig UI does not react to config changes, so the reset button doesn't do anything visually.

**Comment by CoolLKKPS** [comment]
i think doesn't really matter the reset button can work or not for now, in LethalConfig u can reset options one by one, a bit hassle but should be fine
and yea if LethalConfig can automatically refresh by pressing "Refresh" button or trigger by function, that would be great

**Comment by CoolLKKPS** [comment]
@Kesomannen Oh btw don't forget to add Record Player (Unlockable Furniture), i just enter a game and realize can't adjust this volume

**Comment by Kesomannen** [comment]
Turns out the LethalConfig code base is a lot more complicated than I thought. It's quite a chore to go through, so I'm not sure I can add the features needed. I'll close this issue now, but if I manage to make the edits necessary I'll open a PR in LethalConfig, so you can look there.

**Comment by DeathWrench** [comment]
[ObjectVolumeController](https://thunderstore.io/c/lethal-company/p/FlipMods/ObjectVolumeController/) change volume for the record player, tv and boombox. Benefit to using both of these mods is: ObjectVolumeController can change it in game hovering over object also.
